# Generated by Django 3.1.1 on 2021-04-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='description_en_us',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en_us',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_uz',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description_en_us',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='name_en_us',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='name_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='name_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='description_en_us',
            field=models.TextField(null=True, verbose_name='Video Description'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Video Description'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Video Description'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='title_en_us',
            field=models.CharField(max_length=300, null=True, verbose_name='Video Title'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Video Title'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Video Title'),
        ),
    ]
