# Generated by Django 3.1.1 on 2021-04-17 21:28

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210417_0016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'ordering': ['pub_date'], 'verbose_name_plural': 'Biz haqimizda'},
        ),
        migrations.AlterModelOptions(
            name='articlemodel',
            options={'ordering': ['published_at', 'updated_at'], 'verbose_name': 'Maqola', 'verbose_name_plural': 'Maqolalar'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Portfolio rasmlari'},
        ),
        migrations.AlterModelOptions(
            name='videomodel',
            options={'ordering': ['-published_at'], 'verbose_name_plural': 'Videolar'},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about-us-images/%Y/%m/%d/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title_uz',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='author',
            field=models.CharField(default='Mehroj', max_length=50, verbose_name='Avtor'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='caption',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Titr'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='image',
            field=models.ImageField(upload_to='article/%Y/%m/%d/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Chiqarilgan sanasi'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='title',
            field=models.CharField(max_length=350, unique=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sanasi'),
        ),
        migrations.AlterField(
            model_name='images',
            name='caption',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Titr:'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='portfolio-images/%Y/%m/%d/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='caption',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Titr'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='portfolio/%Y/%m/%d/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='short_info',
            field=models.CharField(default='3D model', max_length=500, verbose_name="Qisqa ma'lumot"),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='description',
            field=models.TextField(verbose_name='Video tavsifi'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Video tavsifi'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Video tavsifi'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Video tavsifi'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Video sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Video sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Video sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Video sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/', verbose_name='Video Fayl'),
        ),
    ]
