# Generated by Django 3.1.1 on 2021-04-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210311_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_en_us',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en_us',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_info_en_us',
            field=models.CharField(default='3D model', max_length=500, null=True, verbose_name='Short Info'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_info_ru',
            field=models.CharField(default='3D model', max_length=500, null=True, verbose_name='Short Info'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_info_uz',
            field=models.CharField(default='3D model', max_length=500, null=True, verbose_name='Short Info'),
        ),
    ]
