# Generated by Django 3.1.1 on 2021-04-17 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_ordersingleitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Mijoz', 'verbose_name_plural': 'Mijozlar'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='ordereditem',
            options={'ordering': ['-date_ordered'], 'verbose_name': 'Buyurtma modellar', 'verbose_name_plural': 'Buyurtma modellar'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Buyurtma model', 'verbose_name_plural': 'Buyurtma modellar'},
        ),
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Bajarildi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Buyurtma sanasi'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Bajarildi'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='cart.customer', verbose_name='Mijoz'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan sanasi'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ordered-product/%Y/%m/%d/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='model_quantity',
            field=models.IntegerField(default=0, verbose_name='Model miqdori'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='single_price',
            field=models.FloatField(default=0, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='total_price',
            field=models.FloatField(default=0, verbose_name='Umumiy narx'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Buyurtma sanasi'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.order', verbose_name='Buyurtma'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Miqdori'),
        ),
    ]
